databases:
  - name: rails_project_66
    databaseName: rails_project_66_production
    user: rails_project_66
    plan: free
services:
  - type: web
    name: rails_project_66
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_project_66
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
