# PostgreSQL. Versions 9.3 and up are supported.
# SQLite. Versions 3.8.0 and up are supported.

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3
  timeout: 5000

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: rails_project_66_production
  username: rails_project_66
  password: <%= ENV["RAILS_PROJECT_66_DATABASE_PASSWORD"] %>
